# Generated by Django 2.2 on 2020-11-28 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201128_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 13, 39, 21, 559399, tzinfo=utc)),
        ),
    ]
